# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

####################################### Setup #######################################

# Steps to configure the workflow
# Mandatory                   : #1, #3 & #7
# Custom Private Package      : #2
# Vue & Nuxt App              : #3
# PHP | Laravel App           : #6
# Laravel + Vue / Nuxt App    : #3, #5, & #6

####################################### Setup #######################################

name: github-actions-setup

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:

      #1. Allows access to local files
      # Uncomment the following if not required
      - uses: actions/checkout@v2

      # Use this to install custom private packages from GitHub
      # Uncomment the following if not required
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.ACTIONS_SSH_PRIVATE_KEY }}

      #3. Sets up node js environment and serverless framework
      # Uncomment the following if not required
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm install

      #4. Installs Serverless Framework
      - name: Install Serverless Framework
        run: npm install -g serverless

      #5. This is only required if your project uses Laravel Mix to mix files
      # Use this if you want to load some dependencies to build your project
      - name: Install Laravel Mix
        run: npm install laravel-mix

      #6. Sets up php | laravel environment and composer framework
      # Uncomment the following if not required
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
      - name: Install Composer
        uses: "ramsey/composer-install@v1"
        with:
          composer-options: "--prefer-dist --no-dev"

      #7. Deploys the app using Makefile
      # Uncomment the following if not required....
      - name: Run deployment
        run: make deploy

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
